include $(TOPDIR)/rules.mk

LUCI_TITLE:=Netlink based bandwidth accounting
LUCI_DEPENDS:=+luci-compat +nlbwmon

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
